[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:botocore.*",
    "ignore::DeprecationWarning:boto3.*",
]
addopts = "-v --tb=short"
testpaths = ["tests"]

[tool.black]
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
# A list of directories to exclude from checks
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv", # Your specific exclusion
]

# A list of error codes to ignore
extend-ignore = ["E203", "E501", "F401"]

[tool.sonar]
projectKey = "ajbarea_aws-image-translate"
organization = "ajbarea"
# projectName = "aws-image-translate"
# projectVersion = "1.0"
# sources = "."
# sourceEncoding = "UTF-8"
