// AWS Configuration - Generated by Terraform – do not hand edit

console.log("Config: Loading AWS configuration...");
const AWS_CONFIG = {
  region: "${aws_region}",
  userPoolId: "${user_pool_id}",
  userPoolWebClientId: "${user_pool_web_client}",
  identityPoolId: "${identity_pool_id}",
  bucketName: "${bucket_name}",
  apiGatewayUrl: "${api_gateway_url}",
  lambdaFunctionName: "${lambda_function_name}",
  cloudfrontUrl: "${cloudfront_url}",
  cognitoDomainUrl: "${cognito_domain_url}",
  googleClientId: "${google_client_id}",
};

// Make AWS_CONFIG available globally
window.AWS_CONFIG = AWS_CONFIG;
console.log("Config: AWS_CONFIG loaded:", AWS_CONFIG);
console.log("Config: Current hostname:", window.location.hostname);
console.log("Config: Current protocol:", window.location.protocol);
console.log("Config: Full URL:", window.location.href);

AWS.config.update({
  region: AWS_CONFIG.region,
  logger: { log: function(message) { console.log("AWS SDK:", message); } },
});
console.log("Config: AWS SDK region set to:", AWS.config.region);

if (
  window.location.hostname === "localhost" ||
  window.location.hostname === "127.0.0.1"
) {
  console.log("Config: Development mode - enabling detailed AWS logging");
  AWS.config.logger = console;
}
